# Generated by Django 4.0.3 on 2022-04-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='San_Pham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten_San_Pham', models.CharField(max_length=500)),
                ('Ma_San_Pham', models.CharField(max_length=500)),
            ],
        ),
    ]
